# Generated by Django 5.2.1 on 2025-05-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='base/')),
                ('skill_id', models.CharField(choices=[('1', 'Python'), ('2', 'HTML'), ('3', 'CSS'), ('4', 'Django'), ('5', 'Tailwind'), ('6', 'WordPress')], max_length=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
